[env:esp32cam]
platform = espressif32@6.10.0
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DCORE_DEBUG_LEVEL=1 -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue
lib_deps = bblanchon/ArduinoJson@7.3.1

[env:esp32cam_mic]
extends = env:esp32cam
build_flags = ${env:esp32cam.build_flags} -DENABLE_MIC=1
